[pytest]
# Disable ROS ament plugins to avoid conflicts
# We only need pytest and pytest-cov
addopts = -p no:launch_testing -p no:ament_lint -p no:ament_pep257 -p no:ament_copyright -p no:ament_xmllint -p no:ament_flake8 -p no:launch_testing_ros
testpaths = tests
python_files = *.py
python_classes = Test*
python_functions = test_*
